# Generated by Django 6.0.3 on 2026-03-18 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Unnamed Contract', max_length=255)),
                ('source_code', models.TextField()),
                ('risk_score', models.IntegerField(default=0)),
                ('risk_level', models.CharField(default='Low', max_length=20)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(max_length=255)),
                ('severity', models.CharField(max_length=20)),
                ('line_number', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('fix', models.TextField()),
                ('unsafe_code', models.TextField(default='')),
                ('safe_code', models.TextField(default='')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='analyzer.contract')),
            ],
            options={
                'verbose_name_plural': 'vulnerabilities',
            },
        ),
    ]
